config/routes.rb
MusicShare::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :search
  resources :posts, only: [:create, :destroy, :play,]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/home/filter', to: 'static_pages#home_filtered', via: 'get'
  match '/user/search',  to: 'users#search',  via: 'get'
  match '/youtube/search',  to: 'youtube#search',  via: 'get'
  match '/youtube/post',    to: 'youtube#post', via: 'get'
  match '/posts/like', to: 'posts#like', via: 'post'
  match '/posts/unlike', to: 'posts#unlike', via: 'post'
  match '/posts/increment_play_count', to: 'posts#increment_play_count', via: 'post'
  match '/mobile',  to: 'static_pages#mobile' , via: 'get' 

  # FB Login
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  
end

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="large-12 medium-12 columns">
    <small class="right">
    </small>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="title">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <%= link_to image_tag('logo.png', size: "100"), root_path, :class => 'brand' %>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li>
          <%= link_to (root_path) do %>
            <i class="fi-home fi-large"></i>
          <% end %>
        </li>
        <% if signed_in? %>
          <li>
            <%= link_to (users_path) do %>
              <i class="fi-torsos-all fi-large"></i>
            <% end %>
          </li>
          <li class="has-dropdown">
            <a href="#"><%= image_tag(current_user.image, size: "40") %></a>
            <ul class="dropdown">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body <% if !signed_in? %> class="bg_img" <% end %>>
    <%= render 'layouts/header' %>
    <div id="main" class="container">
      <% flash.each do |name, msg| %>
        <div class="row">
          <div class="large-10 medium-10 large-offset-1 columns">
            <% if msg.is_a?(String) %>
              <div data-alert class="alert-box round success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>  
          </div>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>